# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:

  # Global
  prefix: "adlt"
  postfix: "051"
  location: "northeurope"

  # Feature flags
  enable_private_endpoints: "false"

  # Enable ADE based deployment
  enable_ade_deployment: "false"

  # Terraform remote storage
  terraform_st_resource_group: rg-adl-terraform-state
  terraform_st_storage_account: stadlterraformstate

  # Internals - do not touch
  az_cli_version: 2.45.0
  terraform_st_container_name: default
